[package]
authors = ["LongYinan <longyinan.brooklyn@bytedance.com>"]
edition = "2018"
name = "rust-codegen-win32"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[build-dependencies]
cc = "1"
